- name: stop Tomcat for releasing instance resources
  service: "name={{ item }} state=stopped"
  with_items:
    - tomcat

- name: "Maven install"
  shell: mvn clean install
  args:
    chdir: "{{ proj_dir }}"

- name: restart Tomcat
  service: "name={{ item }} state=restarted"
  with_items:
    - tomcat

- name: Copy citizen.war to Tomcat's directory
  shell: cp {{ proj_dir }}/target/citizen.war {{ tomcat_home }}/webapps/
